### PR TITLE
gfortran 14.2, 13.3, 12.4

### PR DESCRIPTION
**Pull request by h-vetinari**
OSX side of https://github.com/conda-forge/ctng-compilers-feedstock/pull/133

### CODE REVIEW

**Comment by h-vetinari** [comment]
This looks weird:
```
A linker snapshot was created at:
	/tmp/libgcc_s.dylib-2024-05-28-042317.ld-snapshot
ld: Assertion failed: (targetAtom != NULL), function Fixup, file /Users/runner/miniforge3/conda-bld/cctools-and-ld64_1710465551585/work/cctools/ld64/src/ld/ld.hpp, line 826.
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1005: libgcc_s.dylib] Error 1
```
In particular, the path from the cctools feedstock. Looks like some failed relocation?

**Comment by h-vetinari** [comment]
On osx-arm we get:
```
In file included from ../../../libquadmath/math/rem_pio2q.c:2:
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/math.h:53:5: error: #error "Unsupported value of __FLT_EVAL_METHOD__."
   53 | #   error "Unsupported value of __FLT_EVAL_METHOD__."
      |     ^~~~~
make[3]: *** [Makefile:978: math/rem_pio2q.lo] Error 1
```
I thought that might be solvable with a newer SDK, but seems to be another problem. Clang has a [note](https://clang.llvm.org/docs/UsersManual.html#a-note-about-flt-eval-method) about that:
> The `__FLT_EVAL_METHOD__` is not defined as a traditional macro, and so it will not appear when dumping preprocessor macros. Instead, the value `__FLT_EVAL_METHOD__` expands to is determined at the point of expansion either from the value set by the `-ffp-eval-method` command line option or from the target. This is because the `__FLT_EVAL_METHOD__` macro cannot expand to the correct evaluation method in the presence of a `#pragma` which alters the evaluation method. An error is issued if `__FLT_EVAL_METHOD__` is expanded inside a scope modified by `#pragma clang fp eval_method`.

**Comment by h-vetinari** [comment]
I think I found the osx-arm64 issue; fix coming up. For osx-64 we seem to be hitting an assert in ld itself, which looks very similar to https://github.com/NixOS/nixpkgs/issues/105573. There the issue was a very old `-mmacosx-version-min`, and indeed the failing line sets this to the incredibly ancient 10.5!

**Comment by h-vetinari** [comment]
> There the issue was a very old `-mmacosx-version-min`, and indeed the failing line sets this to the incredibly ancient 10.5!

Well, it turns out that this (setting 10.5) happens in the GCC<14 builds as well, but I still have a suspicion that this is related to https://github.com/gcc-mirror/gcc/commit/20b8779ea9bd82b26eeb195b30f695168cd7ae1d somehow.

**Comment by h-vetinari** [comment]
OTOH, assuming the [assert](https://github.com/tpoechtrager/cctools-port/blame/986-ld64-711/cctools/ld64/src/ld/ld.hpp#L826) in ld is valid, we can try to revive https://github.com/conda-forge/cctools-and-ld64-feedstock/pull/70, since that version has a bunch of changes in the [file](https://github.com/tpoechtrager/cctools-port/blame/1009.2-ld64-907/cctools/ld64/src/ld/ld.hpp) where the assert occurs (and before that it's been years since substantial changes therein).

**Comment by h-vetinari** [comment]
@isuruf, if you have any insight or ideas on the `__FLT_EVAL_METHOD__` situation here or the assert in ld for compiling `libgcc=14.1` (but only for the osx-64 to osx-64 native compiler), that would be much appreciated. 🙏

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by fxcoudert** [comment]
Hi, gcc maintainer and macOS developer there. I help ship Homebrew builds for gcc. I have found this and was reading the remaining issues, but the build system is rather convoluted and I'm not entirely sure what are the problems.

If you need any help or advice, let me know how I can help.

In particular, the issues with `__FLT_EVAL_METHOD__` are relatively well-known, so if you can clarify when/where/how they occur, I should be able to help there.

**Comment by h-vetinari** [comment]
Hey @fxcoudert! 👋 

Thanks so much for reaching out, I did notice your name on all the patches we're using here, so I had been toying with the idea of pinging you already.

I'm travelling right now and don't remember all the issues from the top of my head, but will try to answer soon!

**Comment by giordano** [comment]
Today I also ran into the [assertion failure](https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/82#issuecomment-2196119364).  For what is worth, my hackish approach was to force libgcc build system to use a different `-mmacosx-version-min` option, for example 10.8: https://github.com/JuliaPackaging/Yggdrasil/blob/4fb6b23d2032478e41902dba334cb94de2d5c691/0_RootFS/GCCBootstrap%4014/bundled/patches/gcc/gcc1420-Increase-fallback-min-macOS-version-for-libgcc-to-10.8.patch

**Comment by h-vetinari** [comment]
Thank you so much for the reference and the patch @giordano! :)

Finally picking this up again after it had fallen off my radar for too long. Hoping to get this sorted out before GCC 15.1/14.3 get released 🤞

**Comment by h-vetinari** [comment]
@fxcoudert, coming back to this conversation, I still cannot figure out what's going on with
```
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include/math.h:53:5: error: #error "Unsupported value of __FLT_EVAL_METHOD__."
   53 | #   error "Unsupported value of __FLT_EVAL_METHOD__."
      |     ^~~~~
```
I thought it was caused by https://github.com/gcc-mirror/gcc/commit/93f803d53b5ccaabded9d7b4512b54da81c1c616 (because we're on an older SDK), but even reverting that (resp. https://github.com/gcc-mirror/gcc/commit/87e6cc0103369f8891c3c3a516f4d93187c2c12b for GCC 13.3 and https://github.com/gcc-mirror/gcc/commit/65595b02668c99edcfd5aedac984ebcbb64a1685 for 12.4) didn't help. Since you backported those commits, perhaps you understand this better?

Perhaps we're failing to patch the sources in the right place (non-default SDK location) and/or due to permission errors? Or the patch I found is a red herring and it's something else entirely?

@giordano, the good news is that your patch worked for the `osx-64` case! 🥳

**Comment by h-vetinari** [comment]
Sigh, I tested with a macOS 14 SDK (now without the above-mentioned revert), and still the same error 😑 
```
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/math.h:54:5: error: #error "Unsupported value of __FLT_EVAL_METHOD__."
   54 | #   error "Unsupported value of __FLT_EVAL_METHOD__."
      |     ^~~~~
```

**Comment by fxcoudert** [comment]
@h-vetinari that commit at https://github.com/gcc-mirror/gcc/commit/93f803d53b5ccaabded9d7b4512b54da81c1c616 should not need reverting. It should be able to handle both older and newer SDKs. And it is definitely needed for newer SDKs.

Can you confirm what is the difference between the `math.h` from Xcode or command-line tools (`/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/math.h` or something like that), and the one in your build (it will be in `builddir/gcc/include-fixed` if memory serves)? It should include something like this:

```
--- /Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/include/math.h	2024-05-01 00:04:44
+++ /opt/homebrew/opt/gcc/lib/gcc/current/gcc/aarch64-apple-darwin24/14/include-fixed/math.h	2024-08-01 10:46:31
@@ -41,7 +56,7 @@ __BEGIN_DECLS
     taking advantage of GCC's __FLT_EVAL_METHOD__ (which a compiler may
     define anytime and GCC does) that shadows FLT_EVAL_METHOD (which a
     compiler must define only in float.h).                                    */
-#if __FLT_EVAL_METHOD__ == 0 || __FLT_EVAL_METHOD__ == -1
+#if __FLT_EVAL_METHOD__ == 0 || __FLT_EVAL_METHOD__ == -1 || __FLT_EVAL_METHOD__ == 16
     typedef float float_t;
     typedef double double_t;
 #elif __FLT_EVAL_METHOD__ == 1
```

---

Also, I am not sure I understand what you are building exactly. Is it is a cross-compiler or native?

**Comment by fxcoudert** [comment]
I found the list of fixed include files in the build log:

```
2025-03-18T04:21:45.6865410Z pwd; ls -alh include-fixed; echo cp ../../gcc/../fixincludes/README-fixinc include-fixed/README
2025-03-18T04:21:45.6866170Z $SRC_DIR/build_conda/gcc
2025-03-18T04:21:45.6867650Z total 32
2025-03-18T04:21:45.6868930Z drwxr-xr-x    5 runner  staff   160B Mar 18 04:21 .
2025-03-18T04:21:45.6870300Z drwxr-xr-x  803 runner  staff    25K Mar 18 04:21 ..
2025-03-18T04:21:45.6870960Z -rw-r--r--    1 runner  staff   750B Mar 18 04:02 README
2025-03-18T04:21:45.6872610Z -rw-r--r--    1 runner  staff   4.6K Mar 18 04:21 limits.h
2025-03-18T04:21:45.6873530Z -rw-r--r--    1 runner  staff   330B Mar 18 04:21 syslimits.h
2025-03-18T04:21:45.6875370Z cp ../../gcc/../fixincludes/README-fixinc include-fixed/README
```

All the needed Darwin fixes are missing. I think it's because you're building as a cross-compiler, and the fixincludes is not looking for files in the right place. I've not done that in a million years, so I don't remember it well. But there is some doc: https://gcc.gnu.org/onlinedocs/gccint/Header-Dirs.html

I'll try to have a look later today or tomorrow.

**Comment by fxcoudert** [comment]
OK so I got a little further in debugging this.

**For native builds**, you use `--with-native-system-header-dir=/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include` which is weird. `--with-native-system-header-dir` should normally be a relative path (relative to `--with-sysroot`). Unless there is some trick I'm not seeing, I would recommend changing all uses of 

```
--with-native-system-header-dir=$CONDA_BUILD_SYSROOT/usr/include
```

into

```
--with-sysroot=$CONDA_BUILD_SYSROOT
```

**For cross builds**, at least between darwin and darwin, you actually have the headers available and so they should be specified. I believe `--with-sysroot=$CONDA_BUILD_SYSROOT` should do the trick? It is skipped for some reason.

----

I still fail to understand all the use cases of the build script, so I might have missed something. Could you give a little table of all the intended uses (in terms of build, host and target triplets)? I think you do:

- nature x86_64-apple-darwin13.4.0 (in a job named `osx_64_cross_target_platformosx-64gfortran_version12.4.0macos_machinex86_64-apple-darwin13.4.0`)
- another native x86_64-apple-darwin13.4.0 (but this time in a job named `osx_64_cross_target_platformosx-64gfortran_version12.4.0macos_machinex86_64-apple-darwin13.4.0 `??)
- build x86_64-apple-darwin13.4.0, host = target = aarch64-apple-darwin20.0.0
- build = host = x86_64-apple-darwin13.4.0, target = aarch64-apple-darwin20.0.0
- build = host = x86_64-conda-linux-gnu, target = aarch64-apple-darwin20.0.0
- build = host = x86_64-conda-linux-gnu, target = x86_64-apple-darwin13.4.0

**Comment by isuruf** [comment]
The 18 jobs are the following 6 jobs for GCC 12, 13, 14.

build = host = target = x86_64-apple-darwin13.4.0
build = x86_64-apple-darwin13.4.0, host = aarch64-apple-darwin20.0.0, target = x86_64-apple-darwin13.4.0
build = x86_64-apple-darwin13.4.0, host = target = aarch64-apple-darwin20.0.0
build = host = x86_64-apple-darwin13.4.0, target = aarch64-apple-darwin20.0.0
build = host = x86_64-conda-linux-gnu, target = aarch64-apple-darwin20.0.0
build = host = x86_64-conda-linux-gnu, target = x86_64-apple-darwin13.4.0

**Comment by fxcoudert** [comment]
I'm afraid to ask, but for my curiosity: why is there no native aarch64-apple-darwin20.0.0 build? macOS Intel machines are older, slower… Also, Canadian cross compilers are a pain to get working right.

I'll continue investigating in https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/84

The failing case is that of build = x86_64-darwin, host = target = aarch64-darwin. At the moment, it seems that the fixed includes are generated, but then not used during libquadmath, where the SDK headers are pulled instead. I'm not sure why…

PS: technically, I guess the build script could fix the SDK headers themselves, before compiling GCC. That's a hack, but it's a hack that could work…

**Comment by isuruf** [comment]
> why is there no native aarch64-apple-darwin20.0.0 build?

Because we don't have any apple silicon runners on azure. Not yet anyway.

> Also, Canadian cross compilers are a pain to get working right.

True. It took a lot of time to get it right.

**Comment by fxcoudert** [comment]
> Because we don't have any apple silicon runners on azure

🤯 Apple Silicon is only available since… November 2020
